// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerLab.Core.Data;

#nullable disable

namespace PowerLab.Core.Migrations
{
    [DbContext(typeof(PowerLabDbContext))]
    partial class PluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("PowerLab.Core.Models.PluginRegistry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultView")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PluginRegistries");
                });

            modelBuilder.Entity("PowerLab.Core.Models.PluginRegistry", b =>
                {
                    b.OwnsOne("PowerLab.Core.Models.PluginManifest", "Manifest", b1 =>
                        {
                            b1.Property<string>("PluginRegistryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Author")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EntryAssemblyName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Icon")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PluginName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .HasColumnType("TEXT");

                            b1.HasKey("PluginRegistryId");

                            b1.ToTable("PluginRegistries");

                            b1.WithOwner()
                                .HasForeignKey("PluginRegistryId");
                        });

                    b.Navigation("Manifest")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
